name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 
    environment: dev
    steps:
      - name: Download env.sh from another repo
        run: |
          ENV_FILE_URL="https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env"
          curl -sSL "$ENV_FILE_URL" | while IFS= read -r line; do
            secret_value='${{ secrets."$line" }}'
            echo "$line=$secret_value" >> .env
          done
          
        
          # curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env -o .env
          # ls -la
          # cat .env
      # - name: Upload .env as an artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: env
      #     path: .env
