name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  envgen:
    name: envgen
    runs-on: ubuntu-latest
    steps:
      - name: generate env 
        run: |
          curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/env -o envfile
          ls -la
          cat envfile
      - name: Upload .env as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: envfile
          path: envfile
  build: 
    name: Build
    runs-on: ubuntu-latest 
    needs: envgen
    environment: dev
    env:
      BUILD_SECRETS: ${{ secrets[format('{0}', inputs.envfile)] }}
    steps:
      - name: Download artifacts envfile
        uses: actions/download-artifact@v3
        with:
          name: envfile
          
      - name: Download env.sh from another repo
        run: |
          echo "${{ secrets.TEST1 }}" > .env
          ls -la
          cat envfile
      - name: Read envfile and set environment variables
        run: |
          while IFS= read -r line; do
          eval "export $line=\${{ secrets[$line] }}"
          done < envfile
    
      - name: Dynamic env writing
        run: | 
          echo ${{env.BUILD_SECRETS}} 
          echo ${{env.BUILD_SECRETS}} > .envval

          # curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env -o .env
          # ls -la
          # cat .env
                    # ENV_FILE_URL="https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env"
          # curl -sSL "$ENV_FILE_URL" | while IFS= read -r line; do
          #   echo $line
            
          # done
      - name: Upload .env as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
      - name: Upload .envtest as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: envtest
          path: .envtest
      - name: Upload .envtest as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: envval
          path: .envval
