name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      config-repo-ref:
        description: 'main'
        required: true
        default: 'main'
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 
    environment: dev
    steps:
      - name: Checkout config-repo
        uses: actions/checkout@v2
        with:
          repository: PriyeshNayak/DevOps
          ref: ${{ github.event.inputs.config-repo-ref }}
          path: config-repo

      - name: Download env.sh from another repo
        run: |
          cat .env
          
        
          # curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env -o .env
          # ls -la
          # cat .env

      - name: Upload .env as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
