name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  envgen:
    name: envgen
    runs-on: ubuntu-latest
    steps:
      - name: generate env 
        run: |
          curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/env -o envfile
          ls -la
          cat envfile
  build: 
    name: Build
    runs-on: ubuntu-latest 
    needs: envgen
    environment: dev
    env:
      BUILD_SECRETS: ${{ secrets[format('{0}', inputs.envfile)] }}
    steps:
      - name: Download env.sh from another repo
        run: |
          echo "${{ secrets.TEST1 }}" > .env
          ls -la
          cat env
          ls -la envfile
          cat envfile
          
      - name: Dynamic env writing
        run: |
          echo "$BUILD_SECRETS"

          # curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env -o .env
          # ls -la
          # cat .env
                    # ENV_FILE_URL="https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/.env"
          # curl -sSL "$ENV_FILE_URL" | while IFS= read -r line; do
          #   echo $line
            
          # done
      - name: Upload .env as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
