name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download env.sh from another repo
        run: |
          curl -sSL https://raw.githubusercontent.com/PriyeshNayak/DevOps/main/env.sh -o env.sh
          chmod +x env.sh
          ./env.sh 
          cat .env
          
          echo "API_Key=${{secrets.API_KEY}}" >> .envtest
          ls -la
          cat .envtest
      - name: Display environment variables
        run: |
          echo "API_KEY from GitHub Actions environment: $API_KEY"
          echo "DATABASE_URL from GitHub Actions environment: $DATABASE_URL"
          
      - name: Upload .env as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env

      - name: Display contents of env.sh
        run: |
          ls -la
          cat env.sh
          
      - name: Deploy
        run: |
          API_KEY=$(grep 'API_KEY' env_values | cut -d'=' -f2)
          DATABASE_URL=$(grep 'DATABASE_URL' env_values | cut -d'=' -f2)
