name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  envgen:
    name: envgen
    runs-on: ubuntu-latest 
    environment: dev
    steps:
      - name: Extract json envfile
        run: |
          echo "$ALLMYSECRETS" >> env.json
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
          
      - name: Upload .envtest as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env_json
          path: env.json

  build: 
    name: Build
    runs-on: ubuntu-latest 
    needs: envgen
    environment: dev
    steps:
      - name: Download artifacts envfile
        uses: actions/download-artifact@v3
        with:
          name: env_json
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file from repository
        run: |
          cp script.sh .
      - name: Extract env from json
        run: |
          sh script.sh env.json >> .env

      - name: Upload .envtest as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
          
            
