name: Env generation prod

on:
  push:
    branches:
      - main

jobs:
  envgen-prod:
    name: envgen (prod)
    runs-on: ubuntu-latest 
    environment: prod
    steps:
      - name: Extract json envfile
        run: |
          echo "$ALLMYSECRETS" >> env.json
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
          
      - name: Upload .envtest as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env_json
          path: env.json

  extract-prod: 
    name: extract env from json file (prod)
    runs-on: ubuntu-latest 
    needs: envgen-prod
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload script as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: script
          path: script.sh
      - name: Download artifacts envfile and Extract env from json
        uses: actions/download-artifact@v3
        with:
          name: env_json
      - run: |
          ls -la
          sh script.sh env.json >> .env

      - name: Upload .envtest as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
